version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: app-mongodb
    volumes:
      - ./database/data/db:/data/db
    networks:
      - backend
      - database
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongo-express:
    image: mongo-express
    container_name: app-mongoui
    restart: always
    networks:
      - database
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
  backend:
    container_name: app-backend
    build: ./backend
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - "9080:9080"
    environment:
      - MONGODB_CONNECTION_URL
networks:
  frontend:
    name: app_frontend
    driver: bridge
  backend:
    name: app_backend
    driver: bridge
  database:
    name: app-database
    driver: bridge